[build-system]
requires = [
    "setuptools >= 61.0",
    "cffi >= 1.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "textworld"
dynamic = ["version", "optional-dependencies", "dependencies", "readme"]
requires-python = ">=3.8"